### PR TITLE
fix: cargo_template Cargo.toml noise

### LINKED ISSUE #3914: Cargo templates causes errors in cargo checks when projects reference the fluvio repo
# Problem

As of 0.177 cargo parses all Cargo.toml files in the repository generating noisy warnings about the smartmodule and connector project templates.

Projects with a Fluvio git repository dependency generates a lot of noise.

```
$ cargo check
error: invalid inline table
expected `}`
  --> ../../../.cargo/git/checkouts/fluvio-190650900278d481/e180e81/smartmodule/cargo_template/Cargo.toml:11:23
   |
11 | fluvio-smartmodule = {{fluvio-smartmodule-cargo-dependency}}
   |                       ^
   |
error: invalid character `{` in package name: `{{project-name}}`, the first character must be a Unicode XID start character (most letters or `_`)
 --> ../../../.cargo/git/checkouts/fluvio-190650900278d481/e180e81/connector/cargo_template/Cargo.toml:2:8
  |
2 | name = "{{project-name}}"
  |        ^^^^^^^^^^^^^^^^^^
  |
error: invalid inline table
expected `}`
  --> ../../../.cargo/git/checkouts/fluvio-190650900278d481/0e892b2/smartmodule/cargo_template/Cargo.toml:11:23
   |
11 | fluvio-smartmodule = {{fluvio-smartmodule-cargo-dependency}}
   |                       ^
   |
error: invalid character `{` in package name: `{{project-name}}`, the first character must be a Unicode XID start character (most letters or `_`)
 --> ../../../.cargo/git/checkouts/fluvio-190650900278d481/0e892b2/connector/cargo_template/Cargo.toml:2:8
  |
2 | name = "{{project-name}}"
  |        ^^^^^^^^^^^^^^^^^^
  |
```

# Notes
Consider moving smartmodule and connector templates to a separate repository or refactoring Cargo.toml filename generate.

smdk and cdk references would also need to change to reference the new repo

### PR DESCRIPTION
**Pull request by digikata**
fixes #3914

### CODE REVIEW

**Review by EstebanBorai — APPROVED** [review]
Nice catch!

**Comment by pinkforest** [comment]
fyi anything that points to the release git tag is broken atm - either a new release or back-port would be good perhaps ?

**Comment by ajhunyady** [comment]
@digikata, why are we pointing to a git tag?

**Comment by pinkforest** [comment]
Problem with pinning to revision is that things get out of date and don't get updates e.g. security patches

By using tag it uses it in SemVer basis and ensures compatibility within same SemVer

**Pull request merged**
