### PR TITLE
Move CRDs from templates/ to crds/

### PR DESCRIPTION
**Pull request by tothandras**
Is there any reason not to move CRDs to the crds/ folder in `fluvio-sys`?
See: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you

### CODE REVIEW

**Review by sehz — APPROVED** [review]
LGTM

**Review by sehz — CHANGES_REQUESTED** [review]
Looks like CI test fail: https://github.com/infinyon/fluvio/runs/7095527168?check_suite_focus=true.

I think you need to bump chart version

**Comment by sehz** [comment]
CI still fails. Can you find out why it is failing?

**Review by sehz — CHANGES_REQUESTED** [review]
There is no need to bump up major version.  So this should be 0.9.10.

**Review by sehz — APPROVED** [review]
LGTM

**Comment by sehz** [comment]
CI still failed.  Can you check if inline helm still works?  https://github.com/infinyon/fluvio/blob/master/k8-util/helm/Makefile

**Comment by sehz** [comment]
Ensure upgrade helm upgrade works.

**Comment by tothandras** [comment]
@sehz I'm running helm install / upgrade without issues, I'll check the test case.

**Pull request closed without merging**
