### PR TITLE
[Merged by Bors] - Relax platform version requirement for upgrade check

### LINKED ISSUE #1054: Relax platform version comparision
We have logic in the client library to check whether the cluster it has connected to meets a set minimum version. This is in order to make sure that the components that are communicating have the same protocol, etc. However, this version checking is being too specific, which is causing breakages when we are testing out "latest" builds:

```
Existing platform version is different than chart version platform=0.8.1 chart_version=0.8.1-f78f77f947886b894268f9918a369db1aefe1cd6
```

We should relax the version comparison logic to only check the major.minor.patch version compatibility.

### PR DESCRIPTION
**Pull request by nicholastmosher**
Closes #1054.

- Now compares expected platform version to actual platform version using just `major.minor.patch` version components
- Should prevent upgrade error when using a "latest" platform version including a commit hash

### CODE REVIEW

**Review by sehz — CHANGES_REQUESTED** [review]
Looks good but I don't see any test associated with it?

**Review by nacardin — APPROVED** [review]
This works

**Comment by sehz** [comment]
doc test is failing

**Review by sehz — APPROVED** [review]
Looks good for now.  Not sure about testing version checking?

**Comment by nicholastmosher** [comment]
@sehz I extracted the version checking into a function and added some tests 👍

**Review by sehz — APPROVED** [review]

**Pull request closed without merging**
