### PR TITLE
add clippy check to ci

### PR DESCRIPTION
**Pull request by Ryanmtate**
This PR continues the works of #144 to undo the squashed commits that led up to the smoke test failing in CI.

### CODE REVIEW

**Comment by Ryanmtate** [comment]
NOTE: The smoke test errors in 6cff9d5 and b5c3d11 also occur in draft PR #171, which makes me think that the changes in those commits are unrelated to the CI errors. Additionally, these errors are different than the smoke test errors in #144 

...continuing to patch clippy fixes.

**Comment by sehz** [comment]
in: https://github.com/infinyon/fluvio/commit/6cff9d558b002bae51f700aa5d9097f79a05fe3e.

```
Err(err) => {
                     error!("error receiving response: {:?}", err);
                     return Err(KfSocketError::IoError(err));
                     Err(KfSocketError::IoError(err))
                 }
```

this is actual logic change since it now return error instead of just ignoring

**Comment by Ryanmtate** [comment]
> in: [6cff9d5](https://github.com/infinyon/fluvio/commit/6cff9d558b002bae51f700aa5d9097f79a05fe3e).
> 
> ```
> Err(err) => {
>                      error!("error receiving response: {:?}", err);
>                      return Err(KfSocketError::IoError(err));
>                      Err(KfSocketError::IoError(err))
>                  }
> ```
> 
> this is actual logic change since it now return error instead of just ignoring

Is it though? If you reach that match error branch, it would have returned an error `return Err(KfSocketError::IoError(err));`

Clippy suggests dropping the `return` and `;`

**Comment by Ryanmtate** [comment]
Looks like CI tests pass too

**Comment by sehz** [comment]
Sorry, you are right, it is equivalent logic.

**Comment by Ryanmtate** [comment]
@sehz Looks like it works 🎉 

Do you want me to squash these commits before merging?

**Comment by sehz** [comment]
Good work!

sure

**Pull request merged**
