### PR TITLE
[Merged by Bors] - fix: remove `lib-cargo-crate` from `cdk` crate

### PR DESCRIPTION
**Pull request by EstebanBorai**
Reported on https://github.com/infinyon/fluvio/actions/runs/4357510921/jobs/7616904513#step:6:1723
while checking on [latest commit CI results](https://github.com/infinyon/fluvio/commit/7d46304c5cd1daf19601b971622e7305e30df342).

### CODE REVIEW

**Comment by EstebanBorai** [comment]
Hi @galibey! I wonder if you need `lib-cargo-crate` dep for CDK? Given that current CI points out that is not being used?

**Review by sehz — APPROVED** [review]
LGTM

**Review by galibey — APPROVED** [review]
LGTM

**Pull request closed without merging**
