### PR TITLE
2510 - Add Minimum Supported Rust Version Badge

### PR DESCRIPTION
**Pull request by aaronaaeng**
Addresses #2510 by adding an msrv badge to the `README`.  The action runs on every push to `master`.  If a different msrv is needed, the runner commits and pushes the new badge.

### CODE REVIEW

**Review by tjtelan — APPROVED** [review]
LGTM

**Comment by morenol** [comment]
I think that `master` branch is a protected branch so not sure if that push will work without changing the protection rules

**Comment by tjtelan** [comment]
> I think that `master` branch is a protected branch so not sure if that push will work without changing the protection rules

I think you might be right.

I found this [Github Action](https://github.com/marketplace/actions/push-to-status-check-protected-branches) that says it can handle push to protected branches, but we need to provide an access token with the permissions

**Comment by tjtelan** [comment]
https://github.com/infinyon/fluvio/pull/2526 also needs a personal access token created to push to master, so this PR will be unblocked once that occurs

**Pull request closed without merging**
