### PR TITLE
[Merged by Bors] - feat: fvm install help command with usage example

### PR DESCRIPTION
**Pull request by EstebanBorai**
Provides better help message for `fvm install` and also introduces `Usage` examples.

## Demo

CleanShot 2023-10-26 at 11 18 51

### CODE REVIEW

**Comment by ajhunyady** [comment]
Awesome! Thank you.

**Review by digikata — APPROVED** [review]
LGTM, nice!

**Comment by EstebanBorai** [comment]
> Build failed:
> 
> * [Done](https://github.com/infinyon/fluvio/actions/runs/6659039497/job/18097841843)

Cluster timeout. Retrying...

**Pull request closed without merging**
