### PR TITLE
chore: fix fluvio packages channel tag updates

### PR DESCRIPTION
**Pull request by digikata**
in the release, the fluvio packages channel tags did not get updated
a manual run of make bump-fluvio-stable / bump-fluvio-latest seems to show
that fluvio packages runs in an internal dry-run mode unless --release is added.

Oddly enough, the binaries get uploaded but the channel tags do not.
see:

manually updated w/ --release 
- curl https://packages.fluvio.io/v1/packages/fluvio/fluvio/tags/latest
- curl https://packages.fluvio.io/v1/packages/fluvio/fluvio/tags/stable

not corrected yet
- curl https://packages.fluvio.io/v1/packages/fluvio/fluvio-cloud/tags/latest
- curl https://packages.fluvio.io/v1/packages/fluvio/fluvio-cloud/tags/stable
returns 0.2.5, when 0.2.9 was just released

fluvio update / fluvio install seems to be able to operate w/o reference
to the tag value, but some items, such as install.sh use the fp tag urls

### CODE REVIEW

**Comment by morenol** [comment]
shouldn;t this be fixed by?

https://github.com/infinyon/fluvio/commit/93a7046b59e284a1a326e8686b0270e473a183bb

**Comment by morenol** [comment]
I think that at least `make bump-fluvio-latest` is working on CI.  I see that `curl https://packages.fluvio.io/v1/packages/fluvio/fluvio/tags/latest` returns a value that seems to be updated recently

**Review by tjtelan — APPROVED** [review]
🤦 ouch. I added that flag in my testing since there wasn't a `fluvio-packages` build for aarch64. I didn't realize it was live...

**Comment by morenol** [comment]
I just saw that `--release` option is there

**Review by morenol — APPROVED** [review]

**Comment by digikata** [comment]
Ah, I think i had a latest channel install  of fluvio-packages, and that has the "--release" flag in the help.  So I don't think this PR is needed after all.

**Comment by morenol** [comment]
I run `make install-fluvio-package` and I got a version with `--release`  too for the `stable` channel

**Comment by morenol** [comment]
My main doubt is that `curl https://packages.fluvio.io/v1/packages/fluvio/fluvio/tags/latest`

returns 0.10.8-dev-1+91c0784736f62cc9cdc66aa41e929cd83ad35fcf which is the current commit of master (one hour ago) so maybe `make bump-fluvio-latest` is working as expected?

**Comment by digikata** [comment]
Let hold off on merging this PR for now, maybe look at why the fluvio-cloud-ops release-cli didn't update either tag?  Though it's a little less urgent because fluvio update seems to resolve, it would be nice to get a consistent understanding of what's going on here.

**Pull request closed without merging**
