### PR TITLE
[Merged by Bors] - Improve hourly test stability

### LINKED ISSUE #975: Fix hourly test
The hourly tests are failing for 2 reasons.

* The producer stress test (which we are running in benchmark mode) panics due to the load created.
We still want the errors, but the test will still be valuable if it can run to completion. In the future we can make the errors strict again.

* The smoke test has a syntax error in its step.

### PR DESCRIPTION
**Pull request by tjtelan**
* Add CI mode to producer stress benchmark. Producer issues no longer panic. Only print error.
* Fix smoke test matrix var syntax error

Resolves #975

### CODE REVIEW

**Review by sehz — APPROVED** [review]

**Review by sehz — APPROVED** [review]

**Comment by tjtelan** [comment]
@sehz 

The changes to the hourly tests have been tested successfully [here](https://github.com/infinyon/fluvio-perf-test/runs/2395868426?check_suite_focus=true). This is ready to merge

**Review by sehz — APPROVED** [review]
Great!

**Comment by sehz** [comment]
try again:
bors r+

**Pull request closed without merging**
