### PR TITLE
[Merged by Bors] - Fix install fluvio-cloud

### PR DESCRIPTION
**Pull request by nicholastmosher**
Closes https://github.com/infinyon/fluvio/issues/1373

### CODE REVIEW

**Comment by sehz** [comment]
All CI Jobs are failing...

**Comment by nicholastmosher** [comment]
Yowza what happened

**Comment by nicholastmosher** [comment]
GH Actions is "degraded"

image

**Review by morenol — APPROVED** [review]

**Review by sehz — APPROVED** [review]

**Pull request closed without merging**
