### PR TITLE
[Merged by Bors] - (docs) Update --sys-only flag in k8-util/helm/README.md

### LINKED ISSUE #2555: Documentation: wrong flag listed in k8-util/helm/README.md
The [readme] says:
> Then to install sys chart:
> ```
> $ fluvio cluster start --sys
> installing sys chart
> ```
But there is no `--sys` flag. There is a `--sys-only` flag, is that the one that's intended?

[readme]: https://github.com/infinyon/fluvio/blob/master/k8-util/helm/README.md

### PR DESCRIPTION
**Pull request by mfdorst**
Fixes #2555

### CODE REVIEW

**Comment by sehz** [comment]
Can you update PR title to follow convention commit? https://www.conventionalcommits.org/en/v1.0.0/.
We are migrating to automatic changelog generation.  Thanks

**Comment by mfdorst** [comment]
Like that?

**Comment by sehz** [comment]
should be something like: 
```
(docs) Update --sys-only flag in k8-util/helm/README.md
```

**Comment by sehz** [comment]
Great.  Thanks

**Review by sehz — APPROVED** [review]
LGTM

**Pull request closed without merging**
