### PR TITLE
fix(cdk): `sink` generation for conns fails to build

### PR DESCRIPTION
**Pull request by EstebanBorai**

### CODE REVIEW

**Comment by morenol** [comment]
We should have a CI test to catch this

**Review by sehz — CHANGES_REQUESTED** [review]
Yes need to add test to build this

**Comment by EstebanBorai** [comment]
@sehz @morenol currently all our CLI solutions are tested using [BATS](https://bats-core.readthedocs.io/en/stable/index.html) which execute commands
and assert output on it.

The limitation on this approach is that interfaces like the one in `cdk` relies on an interactive terminal which BATS doesn't support, resulting in the following error:

```shell
 Error: IO error: not a terminal
```

As a way to test `generate` integrity, an approach like the one in `smdk generate` could be used:

```bash
smdk generate \
        --no-params \
        --template-path $(pwd)/smartmodule \
        --sm-type filter \
        --sm-public public \
        --silent \
        my-new-sm
```

This approach would still have to be implemented to CDK, this approach limits interactive
prompts to the limit of not showing any of them if all the options are passed as CLI arguments.

**Comment by sehz** [comment]
k.  let's put that as separate issue

**Review by sehz — APPROVED** [review]
Good enough for now.   CI testing as separate issue

**Comment by sehz** [comment]
K8 test are failing

**Pull request merged**
