### PR TITLE
[Merged by Bors] - build: add binary to manifest of connector meta

### PR DESCRIPTION
**Pull request by morenol**

### CODE REVIEW

**Comment by morenol** [comment]
This depends on the binary been on target/release/<connector-name>. Right now we achieve it due to:

https://github.com/infinyon/fluvio/blob/0483f594a7e9e25accd40c8ed56f4064f71476be/.github/workflows/connector-publish.yml#L59

I will try a generic solution so we don't have to run that `cp` before publishing

**Comment by nacardin** [comment]
I'll test now

**Review by galibey — APPROVED** [review]
LGTM

**Review by nacardin — APPROVED** [review]
works!

**Review by EstebanBorai — APPROVED** [review]

**Pull request closed without merging**
