### PR TITLE
[Merged by Bors] - refactor!: replaced `$VERSION` with `$FLV_VERSION` to make it unambigous on install.sh

### LINKED ISSUE #3020: Installer: change version env variable to `FLV_VERSION`
The environment name `VERSION` is too generic.  We should prefix to make it unambigous
see: https://github.com/infinyon/fluvio/issues/3019

### PR DESCRIPTION
**Pull request by viniarck**
Closes #3020

After refactoring, I also explored and executed `./install.sh` using these `FLV_VERSION` values `inexistent`,`latest`, and not set. I've also confirmed that if a `VERSION=inexistent` is set it doesn't interfere as expected.

```
❯ FLV_VERSION=inexistent ./install.sh
fluvio: ⏳ Downloading Fluvio inexistent for x86_64-unknown-linux-musl...
curl: (22) The requested URL returned error: 404
fluvio: ❌ Failed to download Fluvio, could not find custom FLV_VERSION=inexistent
fluvio:     Make sure this is a valid version, or unset FLV_VERSION to download stable
fluvio: 
fluvio: If you believe this is a bug (or just need help),
fluvio: please feel free to file an issue on Github ❤️
fluvio:     https://github.com/infinyon/fluvio/issues/new
```

```
❯ FLV_VERSION=latest ./install.sh
fluvio: ⏳ Downloading Fluvio 0.10.7-dev-1+18c80fbd0ec5a9162aae5024d327097fb593fd46 for x86_64-unknown-linux-musl...
fluvio: ⬇️  Downloaded Fluvio, installing...
fluvio: ✅ Successfully installed /home/viniarck/.fluvio/bin/fluvio-latest
fluvio: ⏳ Downloading Fluvio channel frontend 0.10.7-dev-1+18c80fbd0ec5a9162aae5024d327097fb593fd46 for x86_64-unknown-linux-musl...
fluvio: ✅ Successfully installed /home/viniarck/.fluvio/bin/fluvio
fluvio: ☁️ Installing Fluvio Cloud...
Current channel: stable
fluvio: 🎣 Fetching latest version for package: fluvio/fluvio-cloud...
fluvio: ⏳ Downloading package with latest version: fluvio/fluvio-cloud:0.2.8...
fluvio: 🔑 Downloaded and verified package file

💡 An update to Fluvio is available!
💡     Run 'fluvio update' to install v0.10.6 of Fluvio
fluvio: ☁️ Installing Fluvio Runner...
Current channel: stable
fluvio: ⏳ Downloading package with provided version: fluvio/fluvio-run:latest...
fluvio: 🔑 Downloaded and verified package file

💡 An update to Fluvio is available!
💡     Run 'fluvio update' to install v0.10.6 of Fluvio
fluvio: 🎉 Install complete!
fluvio: 💡 You'll need to add '~/.fluvio/bin/' to your PATH variable
fluvio:     You can run the following to set your PATH on shell startup:
fluvio:       echo 'export PATH="${HOME}/.fluvio/bin:${PATH}"' >> ~/.zshrc
```

```
❯ ./install.sh        
fluvio: ⏳ Downloading Fluvio 0.10.5 for x86_64-unknown-linux-musl...
fluvio: ⬇️  Downloaded Fluvio, installing...
fluvio: ✅ Successfully installed /home/viniarck/.fluvio/bin/fluvio-stable
fluvio: ⏳ Downloading Fluvio channel frontend 0.10.5 for x86_64-unknown-linux-musl...
fluvio: ✅ Successfully installed /home/viniarck/.fluvio/bin/fluvio
fluvio: ☁️ Installing Fluvio Cloud...
Current channel: stable
fluvio: 🎣 Fetching latest version for package: fluvio/fluvio-cloud...
fluvio: ⏳ Downloading package with latest version: fluvio/fluvio-cloud:0.2.8...
fluvio: 🔑 Downloaded and verified package file

💡 An update to Fluvio is available!
💡     Run 'fluvio update' to install v0.10.6 of Fluvio
fluvio: ☁️ Installing Fluvio Runner...
Current channel: stable
fluvio: ⏳ Downloading package with provided version: fluvio/fluvio-run:stable...
fluvio: 🔑 Downloaded and verified package file

💡 An update to Fluvio is available!
💡     Run 'fluvio update' to install v0.10.6 of Fluvio
fluvio: 🎉 Install complete!
fluvio: 💡 You'll need to add '~/.fluvio/bin/' to your PATH variable
fluvio:     You can run the following to set your PATH on shell startup:
fluvio:       echo 'export PATH="${HOME}/.fluvio/bin:${PATH}"' >> ~/.zshrc
```

```
❯ VERSION=inexistent ./install.sh
fluvio: ⏳ Downloading Fluvio 0.10.5 for x86_64-unknown-linux-musl...
fluvio: ⬇️  Downloaded Fluvio, installing...
fluvio: ✅ Successfully installed /home/viniarck/.fluvio/bin/fluvio-stable
fluvio: ⏳ Downloading Fluvio channel frontend 0.10.5 for x86_64-unknown-linux-musl...
fluvio: ✅ Successfully installed /home/viniarck/.fluvio/bin/fluvio
fluvio: ☁️ Installing Fluvio Cloud...
Current channel: stable
fluvio: 🎣 Fetching latest version for package: fluvio/fluvio-cloud...
fluvio: ⏳ Downloading package with latest version: fluvio/fluvio-cloud:0.2.8...
fluvio: 🔑 Downloaded and verified package file

💡 An update to Fluvio is available!
💡     Run 'fluvio update' to install v0.10.6 of Fluvio
fluvio: ☁️ Installing Fluvio Runner...
Current channel: stable
fluvio: ⏳ Downloading package with provided version: fluvio/fluvio-run:stable...
fluvio: 🔑 Downloaded and verified package file

💡 An update to Fluvio is available!
💡     Run 'fluvio update' to install v0.10.6 of Fluvio
fluvio: 🎉 Install complete!
fluvio: 💡 You'll need to add '~/.fluvio/bin/' to your PATH variable
fluvio:     You can run the following to set your PATH on shell startup:
fluvio:       echo 'export PATH="${HOME}/.fluvio/bin:${PATH}"' >> ~/.zshrc
```

### CODE REVIEW

**Review by sehz — CHANGES_REQUESTED** [review]
Nicely Done.  Can you also update reference in as well? https://github.com/infinyon/fluvio/blob/master/DEVELOPER.md

**Comment by viniarck** [comment]
> 3879aeb

Sure thing. Done on this commit [3879aeb](https://github.com/infinyon/fluvio/pull/3117/commits/3879aeb2a41fb43e37a9681be9550caca7b2ec9a).

**Review by sehz — COMMENTED** [review]
LGTM.  thanks!

**Review by sehz — APPROVED** [review]

**Comment by sehz** [comment]
network failures in CI

**Pull request closed without merging**
