### PR TITLE
[Merged by Bors] - Update stable branch on Release action

### PR DESCRIPTION
**Pull request by tjtelan**
https://github.com/infinyon/fluvio-gh-actions-dev/runs/2749536738?check_suite_focus=true -- Test

Cloning the repo w/ `fetch-depth: 0` enables github actions to do our branch rebase during the workflow.

### CODE REVIEW

**Review by nicholastmosher — APPROVED** [review]
LGTM

**Comment by nicholastmosher** [comment]
Do we have any branch protection rules on stable? If so we might need to check whether they're compatible with this.

**Review by sehz — APPROVED** [review]
let's try

**Pull request closed without merging**
