### PR TITLE
rename custom-spu commands to register and unregister; run cargo fmt

### PR DESCRIPTION
**Pull request by Ryanmtate**
@sehz I ran `cargo fmt`, which produced several changes in addition to the renaming `custom-spu` (issue #5). If you would prefer that I do not run `cargo fmt`, happy to force push a reversion.

`cargo test` runs successfully.

### CODE REVIEW

**Comment by Ryanmtate** [comment]
`fluvio custom-spu --help` produces:

```
Custom SPU Operations

fluvio custom-spu <SUBCOMMAND>

FLAGS:
    -h, --help    Prints help information

SUBCOMMANDS:
    register      Register custom SPU
    unregister    Unregister custom SPU
    list          List custom SPUs
    help          Prints this message or the help of the given subcommand(s)
```

**Comment by sehz** [comment]
yes, let's defer ```cargo fmt``` as separate step as part of CI work.

**Comment by Ryanmtate** [comment]
Commit 634dd54 removes `cargo fmt` changes.

**Comment by sehz** [comment]
thanks for contribution!

**Comment by Ryanmtate** [comment]
> thanks for contribution!

no problem!

**Pull request merged**
