### PR TITLE
chore: default to zigbuild for cross-compilation

### PR DESCRIPTION
**Pull request by EstebanBorai**
While working on building the Fluvio image to run in Kubernetes on macOS I found that
cross-compilation of Fluvio might have some incompatibility issues.

In order to speed up development I ended up using `zigbuild` as an alternative to cross-compile Fluvio.

In the future, perhaps it would be nice to detect host's OS and conditionally use `zigbuild` if running on `macOS` for such step.

### CODE REVIEW

**Comment by sehz** [comment]
maybe we should convert default build to use `zigbuild` instead?

**Comment by EstebanBorai** [comment]
> maybe we should convert default build to use `zigbuild` instead?

Lets try that!

**Review by digikata — APPROVED** [review]

**Review by sehz — COMMENTED** [review]
can remove all zig related flags

**Comment by nacardin** [comment]
> can remove all zig related flags

I don't think so, I believe zigbuild only replaces linker, not CC.

**Comment by sehz** [comment]
got it

**Pull request merged**
