### PR TITLE
[Merged by Bors] - Docker image for aarch64

### PR DESCRIPTION
**Pull request by nacardin**
Resolves https://github.com/infinyon/fluvio/issues/1270

### CODE REVIEW

**Comment by nacardin** [comment]
Tested in minikube on EC2 Graviton

**Review by sehz — CHANGES_REQUESTED** [review]
Looking good.  Can you add to changelog?

**Comment by nacardin** [comment]
> Looking good. Can you add to changelog?

Done

**Review by sehz — APPROVED** [review]

**Pull request closed without merging**
