### PR TITLE
[Merged by Bors] - feat: fvm update command

### PR DESCRIPTION
**Pull request by EstebanBorai**
Introduces the `fvm update` command which checks current channel to be up to date.
Channels `stable` and `latest` are both "updateable", in the other hand the static
tag is not "updateable".

### How it works

When a user has either `stable` or `latest` as the active channel, FVM fetches the most
recent release for that channel.

- Stable: Will check if the upstream version is greater than the current using Semver.
- Latest: Will check if the upstream tag is different. We cant tell which is greater because we use SHAs to determine versions.
- Static Tag: When the user has an static tag as version using for instance `fvm install 0.10.14`, FVM will not attempt to update.

Then the same process as for `fvm install` is followed, this is why the logic is first
disengaged from `fvm install` into its own module on commit: [0a8b819](https://github.com/infinyon/fluvio/pull/3645/commits/0a8b8194e409ed3c6f967de6cf7a48b51b002bbb).

In order to determine the current version for the channel FVM uses the already implemented `settings.toml` file.

## Demo

CleanShot 2023-10-31 at 20 58 13

> By changing the version in the settings.toml, we can mimic an outdated version for the active channel.

### CODE REVIEW

**Comment by ajhunyady** [comment]
What happens if I run `fvm update` and there is not new image?

**Comment by EstebanBorai** [comment]
> What happens if I run `fvm update` and there is no new image?
> 
> 

You will see:

```
You are up to date
```

**Comment by EstebanBorai** [comment]
> What happens if I run `fvm update` and there is no new image?

Just added a test for this here: https://github.com/infinyon/fluvio/pull/3645/commits/b592395b2090dbc40acabdabeb2e73033d322b66#diff-9e90aaedcb1d6ed2a0448f1c8fb5306d2c9788f1ed82e0d22619efb9f2f277e2R745-R768

**Review by digikata — APPROVED** [review]
Looks good!

**Pull request closed without merging**
