### PR TITLE
[Merged by Bors] - Fix Fluvio log directory on K8

### LINKED ISSUE #539: [Bug]:  SPU on K8 uses /tmp/fluvio as data dir
On K8, SPU runs with `--log-base-dir /tmp/fluvio` so its not using the PV mounted at `/var/lib/fluvio/data`

**Describe the setup**
Minikube / Fluvio Cloud

**How to reproduce it**
1. Install cluster to minkube
2. Run `kubectl get pod flv-spg-main-0 -o yaml`

Container args shows `log-base-dir` value. Should be `/var/lib/fluvio/data`, not `/tmp/fluvio`.

### PR DESCRIPTION
**Pull request by nicholastmosher**
Fixes #539.

- Changes remaining Specs to use `/var/lib/fluvio/data`
- Changes local development data directory to `~/.fluvio/data/`

### CODE REVIEW

**Comment by nicholastmosher** [comment]
Will update to use `~/.fluvio/data` as the development data directory.

**Review by sehz — APPROVED** [review]
LGTM

**Comment by sehz** [comment]
Update chanelog and bump up platform version

**Comment by sehz** [comment]
And bump up version for this crate as well

**Review by nacardin — APPROVED** [review]
K8 and Local stores data at
`/var/lib/fluvio/data` and `~/.fluvio/data` respectively

**Pull request closed without merging**
