### PR TITLE
[Merged by Bors] - Switch to Clap from StructOpt

### LINKED ISSUE #1805: Remove versions from displaying in CLI subcommands
% fluvio consume -h
fluvio-consume 0.0.0

### LINKED ISSUE #2166: Upgrade CLI to use Clap v3 over StructOpt
Looks like all the functionality of [`StructOpt` has been added to Clap](https://github.com/TeXitoi/structopt#maintenance):

> As clap v3 is now out, and the structopt features are integrated into (almost as-is), structopt is now in maintenance mode: no new feature will be added.
> 
> Bugs will be fixed, and documentation improvements will be accepted.

Doesn't look too hard: https://github.com/clap-rs/clap#example

### LINKED ISSUE #2283: ZSH autocompletions
Once we move to clap we can enable again zsh autocompletions.

### PR DESCRIPTION
**Pull request by thehabbos007**
Hello!

I really like the project, and decided to tackle some issues :)

This resolves #2166 in https://github.com/infinyon/fluvio/pull/2281/commits/9636cc342eb9f3691d658cb62a7f13b248515ed2

CLI smoke tests pass locally for me with the switch to `Clap`, and I've made sure to mirror the same configurations that `StructOpt` was using, such as no coloring, suggestions etc.

ZSH completions have been re-enabled as they work with clap now!

(gave the branch an irrelevant name before, sorry!)

Edit:
Also resolves #1805 and resolves #2283

### CODE REVIEW

**Comment by morenol** [comment]
hey, could you separate this into two PRs?

**Review by tjtelan — CHANGES_REQUESTED** [review]
CI test failed: https://github.com/infinyon/fluvio/runs/5795357803?check_suite_focus=true

Can you update `fluvio-extension-common`'s crate version to `0.7.3`, please?

**Comment by sehz** [comment]
please rebase to resolve conflict

**Comment by thehabbos007** [comment]
I didn't make it clear from the PR description, but I've also re-enabled ZSH completions (they work now with clap). Would you like that to be added to the changelog or somewhere else?

**Comment by morenol** [comment]
> I didn't make it clear from the original PR description, but I've also re-enabled ZSH completions (they work now with clap). Would you like that to be added to the changelog or somewhere else?

Yes, could you create an issue and add that to the changelog in this PR?

I think that this is also being fixed https://github.com/infinyon/fluvio/issues/1805

**Comment by thehabbos007** [comment]
Making the changelog updates now. Regarding the reason why this was fixed with clap, I am not sure because the previous `StructOpt` based CLI would just panic and instruct creating a error report, so I can't pinpoint any commit/version without digging further into clap

**Review by morenol — APPROVED** [review]
LGTM

**Comment by sehz** [comment]
@tjtelan ?

**Review by tjtelan — APPROVED** [review]

**Comment by sehz** [comment]
This cause CD failure:  https://github.com/infinyon/fluvio/runs/5824039728?check_suite_focus=true

**Comment by thehabbos007** [comment]
@sehz the same timeout also happened in one of the CI runs, but ran normally after an additional commit. Do you think some command in the CLI has been improperly translated, or could it k3d flakiness? I can try to investigate further later today

**Pull request closed without merging**
