### PR TITLE
[Merged by Bors] - chore: developer help

### PR DESCRIPTION
**Pull request by davidbeesley**
Fixes a small typo here `make -C k8-util/helm/clean`

### CODE REVIEW

**Comment by sehz** [comment]
Helm building is invoked https://github.com/infinyon/fluvio/blob/master/crates/fluvio-cluster/build.rs

**Comment by davidbeesley** [comment]
Ok I'm sure I was did something wrong when I built it the first time then.

**Review by sehz — APPROVED** [review]
LGTM.  thanks for fixing doc

**Pull request closed without merging**
