### PR TITLE
[Merged by Bors] - fix: use consistent naming for connector config example file

### PR DESCRIPTION
**Pull request by EstebanBorai**
Currently we have `sample-config.yaml` as our connector config template filename and `config-example.yaml` for other connector examples. In order to keep it consistent, rename template to use `config-example.yaml`.

### CODE REVIEW

**Comment by galibey** [comment]
`cdk test` uses this name as the default value. You might want to change there too: https://github.com/infinyon/fluvio/blob/f619f5932a8e20e67e33b5c52cac03bc7576e711/crates/cdk/src/test.rs#L18

**Comment by EstebanBorai** [comment]
> `cdk test` uses this name as the default value. You might want to change there too: https://github.com/infinyon/fluvio/blob/f619f5932a8e20e67e33b5c52cac03bc7576e711/crates/cdk/src/test.rs#L18

Thanks so much @galibey!

**Comment by EstebanBorai** [comment]
@galibey PR updated with the rename! Thanks so much for pointing it out!

**Review by digikata — APPROVED** [review]
LGTM

**Pull request closed without merging**
