### PR TITLE
[Merged by Bors] - Fix broken doc links

### PR DESCRIPTION
**Pull request by mfdorst**
This is a quick fix for #2546.

### CODE REVIEW

**Review by sehz — CHANGES_REQUESTED** [review]
Thanks for PR.

However, I would rather keep `deny`.   Instead, should perform these steps:
* Fix broken link
* Add steps in CI to check for doc link

**Comment by mfdorst** [comment]
Okay sure I can do that

**Comment by sehz** [comment]
can you rebase to master? this should fix clipping issue

**Review by tjtelan — APPROVED** [review]
LGTM

**Review by sehz — APPROVED** [review]
LGTM

**Comment by sehz** [comment]
Thanks for PR.

**Pull request closed without merging**
