### PR TITLE
CWE

### PR DESCRIPTION
**Pull request by bohlmannc**
# What does this PR do?

This PR adds a new option for consuming called `end-offset` in order to cease reading from the stream when the ending offset is found in the stream's current record, instead of waiting for new inputs.
 
# Motivation

Helping out on good first issues.

# Related issues

A list of issues closed by or relevant to this PR.

- Supports [#1898] (https://github.com/infinyon/fluvio/issues/1898)
- Closes [#1940] (https://github.com/infinyon/fluvio/issues/1940).

# Additional Notes

None

# Checklist

- [ ] Created or updated all relevant documentation
- [ ] Added unit tests to relevant added or changed code
- [ ] Bumped required crate version numbers
- [ ] Updated CHANGELOG.md

### CODE REVIEW

**Comment by bohlmannc** [comment]
I don't understand why I keep having problems with the Rust check fmt test. If you look at commit 6d82349 above, the changes don't show the duplication error that arises in the Details of the failed test. There's some sort of incongruency.

**Comment by sehz** [comment]
Have you tried `cargo fmt`?

**Comment by sehz** [comment]
You can run same check locally:  `make check-fmt`

**Comment by morenol** [comment]
@bohlmannc  could you rebase and then update the changelog? It looks like CI is failing because it doesnt have the latest changes on fluvio crate

**Pull request closed without merging**
