### PR TITLE
[Merged by Bors] - feat(smdk): support `lookback` in test

### LINKED ISSUE #3315: Add support of `lock_back` to SMDK tool
We should provide an ability to test `look_back` functions in SMDK tool.

### PR DESCRIPTION
**Pull request by galibey**
Added an ability to specify the lookback parameter and provide existing records to simulate data in the topic.

For example, here we run `test` and pass input record "1" and provide other records "2" and "3" as they would exist in the topic before:
```bash
smdk test --text "1" --lookback-last 1 --record "2" --record "3" 
```
the `look_back` function will receive record "3".

Closes #3315

### CODE REVIEW

**Review by sehz — CHANGES_REQUESTED** [review]
Can we add CLI test?

**Comment by galibey** [comment]
> Can we add CLI test?

added in https://github.com/infinyon/fluvio/pull/3317/commits/d1d962aaf5502334b4c02441f626a9c73e16b02a

**Review by sehz — APPROVED** [review]
Nice

**Pull request closed without merging**
