### PR TITLE
[Merged by Bors] - fix: added cli tests for smdk load

### LINKED ISSUE #2863: [Bug]: Smdk doesn't load into cluster
**What happened**
`smdk load` fails

**Expected behavior**
not fail

**Describe the setup**
```
fluvio version
Release Channel      : stable
Fluvio CLI           : 0.10.2
Fluvio CLI SHA256    : 61808537aa82f7dceb24cfa5cc112cbb98fe507688ebd317afae2fe44f2a0f5e
Fluvio channel frontend SHA256 : b9a07efe2b251d77dd31d65639b1010b03fa1dd34524d957bcc2e5872f80ee65
Fluvio Platform      : 0.10.2 (infinyon-cloud)
Git Commit           : 75be9c2003dbc22d3e8c2da20cb73841725b410a
OS Details           : Darwin 13.0.1 (kernel 22.1.0)
=== Plugin Versions ===
Fluvio Runner (fluvio-run)     : 0.0.0
Infinyon Cloud CLI (fluvio-cloud) : 0.2.5
```

**How to reproduce it (as minimally and precisely as possible)**
Following steps in the doc:
```
$ smdk generate my-filter
$ cd my-filter/
$ smdk build
$ smdk load

Loading package at: /Users/sehyo/git/infinyon/smtest/my-filter
Found SmartModule package: my-filter
Error: No such file or directory (os error 2)
```

**Environment (please complete the following information):**
 - OS: [Mac]
 - Fluvio Version [0.10.2]

### PR DESCRIPTION
**Pull request by galibey**
Fixes #2863

### CODE REVIEW

**Review by davidbeesley — CHANGES_REQUESTED** [review]
Since I believe `smkd test` is also affected by this, I would add a few tests to make sure that is also working as expected.

**Comment by galibey** [comment]
> Since I believe `smkd test` is also affected by this, I would add a few tests to make sure that is also working as expected.

added tests for `smdk test`

**Review by davidbeesley — APPROVED** [review]
Thanks. LGTM

**Pull request closed without merging**
