### PR TITLE
[Merged by Bors] - Bump fluvio-future

### LINKED ISSUE #1629: HandshakeError does not expose underlying error
We only see the following for any connection error:
```
❯ fluvio topic list                                                                          
Error: 
   0: Fluvio client error
   1: Fluvio socket error
   2: HandshakeError
```

This may be something that needs to be fixed in our futures crate.

### PR DESCRIPTION
**Pull request by morenol**
Closes  #1629

### CODE REVIEW

**Comment by sehz** [comment]
Is there other crates that need to updated their version of fluvio future?

**Comment by morenol** [comment]
We may enforce all the crates to use fluvio-future>=0.3.12 but I dont think that it is necessary now. Should we do that?

 I am just updating Cargo.lock with that so the binaries and docker images created use that.

**Comment by sehz** [comment]
Only for crates need to depend for some explicit behavior.  This is mainly for external crates which may not pick up behavior changes

**Comment by morenol** [comment]
ok, will add that to fluvio client, not sure if we need that elsewhere, this fluvio-future update includes the display representation update for its error type

**Review by sehz — APPROVED** [review]
LGTM

**Pull request closed without merging**
