### PR TITLE
[Merged by Bors] - Add exe suffic for windows targets

### LINKED ISSUE #1369: Windows client support
This issue tracks all of the tasks that need to be done in order to have full support for Windows users, including installation experience.

- [x] #1370
- [x] #1371
- [ ] #1372

### LINKED ISSUE #1372: Update `fluvio install` to work properly on Windows
Currently, `fluvio install some-plugin` will only work for Unix environments because it assumes the path to Fluvio's directory is `~/.fluvio`. We should expand this to work with Windows as well. We need to decide what Fluvio's "home directory" should be, I think probably it should be something like:

```
%APPDATA%\Roaming\fluvio
```

Or another `%APPDATA%` folder, I don't know their exact purposes.

### PR DESCRIPTION
**Pull request by simlay**
Closes #1369.
Closes #1372.

### CODE REVIEW

**Review by nicholastmosher — APPROVED** [review]
The code looks good, but I don't have a windows machine to test it. If you've tested it and everything works, I'm good with it 👍

**Comment by simlay** [comment]
bors retry

**Comment by simlay** [comment]
bors retry

**Pull request closed without merging**
