### PR TITLE
[Merged by Bors] - fix: sc should use namespace in k8 mode

### PR DESCRIPTION
**Pull request by nacardin**

### CODE REVIEW

**Review by galibey — APPROVED** [review]
LGTM

**Comment by EstebanBorai** [comment]
@nacardin , @galibey this is being retried after merging #3660

**Comment by EstebanBorai** [comment]
Error looks now related to Helm Client https://github.com/infinyon/fluvio/actions/runs/6737878054/job/18316519105#step:13:54, retrying.

**Comment by EstebanBorai** [comment]
bors retry

**Pull request closed without merging**
