### PR TITLE
[Merged by Bors] - feat: Update fluvio profile export to have the same format that `FluvioConfig`

### PR DESCRIPTION
**Pull request by morenol**
With this change, we can run `fluvio profile export` > profile.json

And then use the generated json to create client in microservices/lambda services, etc

### CODE REVIEW

**Comment by sehz** [comment]
how this will work existing profile?

**Comment by morenol** [comment]
I think that this will work with any existing profile, the only difference is in the output of `fluvio profile export`. Not sure why we had that ProfileExport wrapper other than maybe the camelCase change? @nacardin

**Comment by morenol** [comment]
Maybe is for the  TlsConfig::Files case?

```rust
                    TlsConfig::Files(_) => {
                        return Err(anyhow!("Cluster {cluster_name} uses externals TLS certs. Only inline TLS certs are supported."))
                    }
```

**Comment by nacardin** [comment]
> I think that this will work with any existing profile, the only difference is in the output of `fluvio profile export`. Not sure why we had that ProfileExport wrapper other than maybe the camelCase change? @nacardin

This was done to support the swift client. I think we ran into issues with ffi at the time with `swift_bridge`.

**Review by nacardin — APPROVED** [review]
Looks good! It will break the workflow for the swift client but we can try to update it to use the new format or if not possible, provide a tool as part of it to do the conversion.

**Comment by morenol** [comment]
bors retry

**Comment by sehz** [comment]
CI failure for Windows:
```
error[E0433]: failed to resolve: use of undeclared crate or module `fluvio_cluster`
 --> crates/fluvio-cli/src/profile/export.rs:7:5
  |
7 | use fluvio_cluster::fluvio_config::TlsPolicy::Verified;
  |     ^^^^^^^^^^^^^^ use of undeclared crate or module `fluvio_cluster`
```

**Comment by morenol** [comment]
> CI failure for Windows:
> 
> ```
> error[E0433]: failed to resolve: use of undeclared crate or module `fluvio_cluster`
>  --> crates/fluvio-cli/src/profile/export.rs:7:5
>   |
> 7 | use fluvio_cluster::fluvio_config::TlsPolicy::Verified;
>   |     ^^^^^^^^^^^^^^ use of undeclared crate or module `fluvio_cluster`
> ```

Fixed in last commit, I was doing an import using a crate that is not installed when building for windows

**Pull request closed without merging**
