### PR TITLE
Fix/action/fluvio/darwin

### PR DESCRIPTION
**Pull request by Ryanmtate**
fixes fluvio GH action for macos

### CODE REVIEW

**Comment by Ryanmtate** [comment]
This is now working for https://github.com/infinyon/fluvio-demo-apps-node/pull/11

Ready for review / merge.

**Review by sehz — APPROVED** [review]

**Comment by sehz** [comment]
is still valid? if so, can you rebase

**Comment by Ryanmtate** [comment]
Yes, this is still valid; required for fluvio gh action.

**Comment by Ryanmtate** [comment]
actually; maybe not, closing this as extraneous.

**Pull request closed without merging**
