### PR TITLE
chore: rename SpuSocket to StreamSocket

### PR DESCRIPTION
**Pull request by fraidev**
New function to create streaming connection. 
Will be necessary for mirroring sc-to-sc connection.

Usage: https://github.com/infinyon/fluvio/blob/1c0022c1d1db2fd11197334e59a49f8eac959f53/crates/fluvio-sc/src/controllers/mirroring/controller.rs#L91

### CODE REVIEW

**Comment by sehz** [comment]
There is already `WatchRequest`.  Is there need to create different one?

**Comment by fraidev** [comment]
> There is already `WatchRequest`. Is there need to create different one?

I guess so, `watch` only works for `Spec` objects, for mirroring I need by `Request`.

**Comment by sehz** [comment]
same code exists here: https://github.com/infinyon/fluvio/blob/master/crates/fluvio/src/spu.rs.   Let's consolidate them to make it common.

**Comment by fraidev** [comment]
> same code exists here: https://github.com/infinyon/fluvio/blob/master/crates/fluvio/src/spu.rs. Let's consolidate them to make it common.

Indeed! It's the same code. 

I propose to rename `SpuSocket` to something more “generic” as we want it for SC too now.
What do you think?

**Review by sehz — APPROVED** [review]
LGTM

**Pull request merged**
