### PR TITLE
chore: fix rules of clippy 1.78.0

### PR DESCRIPTION
**Pull request by fraidev**
Fixing this clippy error:

```
error: direct implementation of `ToString`
  --> crates/fluvio-smartmodule-derive/src/ast.rs:36:1
   |
36 | / impl ToString for SmartModuleKind {
37 | |     fn to_string(&self) -> String {
38 | |         let string = match self {
39 | |             SmartModuleKind::Init => "init",
...  |
49 | |     }
50 | | }
   | |_^
   |
   = help: prefer implementing `Display` instead
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#to_string_trait_impl
   = note: `-D clippy::to-string-trait-impl` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::to_string_trait_impl)]`
   ```

### CODE REVIEW

**Review by EstebanBorai — APPROVED** [review]

**Comment by EstebanBorai** [comment]
Hey @fraidev! Do you think you can also update: https://github.com/infinyon/fluvio/blob/master/rust-toolchain.toml as part of this PR to point to `1.78.0` please?

**Comment by fraidev** [comment]
> Hey @fraidev! Do you think you can also update: https://github.com/infinyon/fluvio/blob/master/rust-toolchain.toml as part of this PR to point to `1.78.0` please?

Done! I needed more changes too.

**Review by EstebanBorai — APPROVED** [review]
Nice update!

**Comment by EstebanBorai** [comment]
Thanks for reviewing all updates @fraidev!

**Pull request merged**
