### PR TITLE
[Merged by Bors] - fix: unblock cd_dev.yaml

### PR DESCRIPTION
**Pull request by digikata**
narrow workaound, use FLV_VERSION because last dev version install.sh is being used in CD_Dev in order to release next install.sh

### CODE REVIEW

**Comment by morenol** [comment]
I think with a pre-release, the script will be updated so this won't be needed

**Review by morenol — APPROVED** [review]

**Comment by digikata** [comment]
I think even w/ pre-release set, the release ci checks that the last CD_Dev suceeded. This should get the reverted install.sh installed onto the latest channel, so everything else downstream will work.

**Comment by morenol** [comment]
bors retry

**Comment by morenol** [comment]
bors retry

**Pull request closed without merging**
