### PR TITLE
[Merged by Bors] - Adding timeouts to hourly test

### LINKED ISSUE #983: CI - Add timeouts to hourly test
This is urgent! The hourly tests are not terminating in CI, and they are wasting a lot of build minutes.

I want the test to fail gracefully, so I'm going to set the shortest timeout on the `flv-test` run. If for some reason, compilation takes long for flv-test, I'll have another timeout on that step. And I want to shorten the default timeout from 60 min to 20 min.

* 10 min timeout on flv-test
* 15 min timeout on the step
* 20 min max on the entire job

### PR DESCRIPTION
**Pull request by tjtelan**
* 10 min timeout on flv-test to allow graceful fail handling by test
* 15 min timeout on the step to catch slow compilation
* 20 min max on the entire job

Attempting to fail gracefully first
Resolve #983

### CODE REVIEW

**Review by sehz — APPROVED** [review]

**Comment by tjtelan** [comment]
The tests still don't pass, unfortunately. But the timeouts shorten the wait and free up the custom runner in less than an hour. https://github.com/infinyon/fluvio-perf-test/actions/runs/769581747

More info is added in the producer stress test so we can track the execution of the loop.

This is ready to merge

**Comment by sehz** [comment]
bors +r

**Comment by sehz** [comment]
bor

**Comment by sehz** [comment]
bors +r

**Pull request closed without merging**
