### PR TITLE
[Merged by Bors] - Partition list

### LINKED ISSUE #1181: `fluvio partition list` should sort by Topic, then by Partition number
Currently, whenever we use `fluvio partition list`, the output comes out in no particular order

```
 TOPIC  PARTITION  LEADER  REPLICAS  RESOLUTION  HW  LEO  LSR  FOLLOWER OFFSETS
 multi  3          0       []        Online      5   5    0    []
 multi  2          0       []        Online      3   3    0    []
 multi  0          0       []        Online      0   0    0    []
 multi  4          0       []        Online      2   2    0    []
 multi  1          0       []        Online      0   0    0    []
```

It is confusing to read this, because the partitions are out of order. Even worse, when there are multiple Topics, then the partitions of many topics can get mixed among each other. We should sort this list:

- First sort by Topic,
- Then sort by Partition number

With this fix, the above list should instead look like:

```
TOPIC  PARTITION  LEADER  REPLICAS  RESOLUTION  HW  LEO  LSR  FOLLOWER OFFSETS
multi  0          0       []        Online      0   0    0    []
multi  1          0       []        Online      0   0    0    []
multi  2          0       []        Online      3   3    0    []
multi  3          0       []        Online      5   5    0    []
multi  4          0       []        Online      2   2    0    []
```

### PR DESCRIPTION
**Pull request by nicholastmosher**
Closes #1181 and fixes the typo of `LSR` to `LRS`, per @ajhunyady's request.

- Note I only fixed the typos in non-breaking ways (i.e. comments and local variables), I did not edit spec fields

### CODE REVIEW

**Comment by ajhunyady** [comment]
Thanks @nicholastmosher

**Review by sehz — APPROVED** [review]
LGTM.  Nice small changes!

**Comment by nicholastmosher** [comment]
Seems like we might be experiencing some flakiness in the upgrade test? I think I have seen this before and that it works when retrying:

image

I'm going to give this another shot to confirm whether it is just flaky and I'll open an issue.

bors r+

**Pull request closed without merging**
