### PR TITLE
[Merged by Bors] - Remove sccache to see if perf is impacted

### PR DESCRIPTION
**Pull request by nicholastmosher**
Let's compare with current CI workflow to see if anything actually runs slower without sccache.

### CODE REVIEW

**Comment by sehz** [comment]
Looks like removing `sccache`  either improved or no impact at all.  Like it!

**Comment by nicholastmosher** [comment]
@sehz do we want to try merging this and worse case we can revert it? It'll be hard to test the "release mode" workflow otherwise

**Comment by sehz** [comment]
Can we always revert. let's merge it!

**Review by sehz — APPROVED** [review]

**Pull request closed without merging**
