### PR TITLE
fix: restrict cluster commands based on profile

### LINKED ISSUE #3619: Restrict `cluster` commands based on current profile
Currently, fluvio cli may confuse users when operating on clusters because it's not always clear if they're running against a `cloud` or `local` profile. We should improve user experience by restricting which commands can be run depending on the current profile and providing a helpful error message.

---

We should restrict most of the `fluvio cluster` commands and display a helpful error message when the current profile is pointing to `cloud`:

```sh
$ fluvio profile
 cloud
$ fluvio cluster check
 Invalid command on `cloud`. Switch to `local` profile or start a `local` cluster and try again. 
```

the only exception is `fluvio cluster start`, which should work regardless of the current profile.

```sh
$ fluvio profile
 cloud
$ fluvio cluster start
 (start a local cluster)
$ fluvio profile
 local
```

### PR DESCRIPTION
**Pull request by matheus-consoli**
Closes #3619

Check the current profile to restrict which commands are available.

Also, improve the error message when there's no profile:

```diff
$ fluvio cluster check
-Config error: Config has no active profile
+no profile available, create a local cluster or log in to InfinyOn Cloud
```

### CODE REVIEW

**Comment by matheus-consoli** [comment]
CI failed because the tests were creating a fake cloud profile pointing to an unreal address.

It seems that the tests weren't executing commands particularly related to these, so I changed the tests to create a fake cloud cluster pointing to the local cluster.

**Comment by ajhunyady** [comment]
@digikata that's correct. I thought we captured that at some point when we discussed the PRD.

**Comment by digikata** [comment]
I found this note on the cluster cleanup PRD, but it's a little obscure https://github.com/infinyon/roadmap/blob/c74519c8adb9ec049f679d977aba581601eb2396/prd/cluster-cleanup.md?plain=1#L168

**Comment by ajhunyady** [comment]
> I found this note on the cluster cleanup PRD, but it's a little obscure https://github.com/infinyon/roadmap/blob/c74519c8adb9ec049f679d977aba581601eb2396/prd/cluster-cleanup.md?plain=1#L168

I think the summary above is a bit more thoughtful. We should debate that instead. I think multi-cluster cares more about naming conventions than anything else. 

From this requirement point of view, all those clusters would be of the same `infinyon-cloud` type.

**Comment by sehz** [comment]
Yes, we decide to add `profile type`.   One is `infinyon`, other is `local`?

**Comment by ajhunyady** [comment]
> Yes, we decide to add `profile type`. One is `infinyon`, other is `local`?

Yes, parts of that is captured in the doc (Yes) for INFINYON.

**Review by digikata — APPROVED** [review]

**Comment by matheus-consoli** [comment]
@digikata, this is not ready for merging yet, I need to update it to use the cluster metadata.
I market it as a draft for now

**Pull request closed without merging**
