### PR TITLE
4099 produce config debug

### LINKED ISSUE #4099: better developer support for produce config
Make it easier to diagnose producer config while developing client.

- Enable `debug` derive in the TopicProducerConfig
- Add accessor to properties.  Currently they are not public so can't access config once created.

And expose, topic and config in the `TopicProducer`

### PR DESCRIPTION
**Pull request by diogopontual**
to fix #4099  ,  I did:

1. Create accessor fn for the properties on TopicProducerConfig;
2. Derive Debug;
3. Ignore debug for Box<dyn Partitioner + Send + Sync>;
4. Expose topic and config on TopicProducer;

It is unclear (at least for me :D) if these "non-functional" changes must be unit-tested in some fashion. I am more than happy to implement the needed tests.

flujvio

Thank you

### CODE REVIEW

**Comment by sehz** [comment]
can you rebase?

**Comment by sehz** [comment]
otherwise looks good

**Review by sehz — APPROVED** [review]

**Comment by diogopontual** [comment]
Hey, @sehz, the branch has already been updated.

**Comment by sehz** [comment]
clippy failure

**Pull request merged**
