### PR TITLE
[Merged by Bors] - chore: configure fluvio-run build for armv7

### PR DESCRIPTION
**Pull request by digikata**

### CODE REVIEW

**Review by sehz — APPROVED** [review]
LGTM. Nice work

**Comment by morenol** [comment]
@digikata there is a compilation issue related to one of the last changes added to main, let me create a PR for that

**Comment by morenol** [comment]
PR created @digikata  https://github.com/infinyon/fluvio/pull/3459

**Comment by morenol** [comment]
bors retry

**Pull request closed without merging**
