### PR TITLE
[#3810] forbid start when should be resumed

### PR DESCRIPTION
**Pull request by avikam**
Completing issue [3810](https://github.com/infinyon/fluvio/issues/3810).
This change adds a pre-flight check to the local installation mode, to verify no previous local config file exists, as an indication to a cluster that wasn't properly deleted.

### CODE REVIEW

**Comment by drc-infinyon** [comment]
@digikata can you triage please.

**Comment by digikata** [comment]
The detection looks good, but probably needs a bats test.

This sequence fails to resume:

```
$ fluvio cluster start 
📝 Running pre-flight checks
    ✅ Local Fluvio is not installed
    ✅ Previous local fluvio installation not found
🎉 All checks passed!
✅ Local Cluster initialized
👤 Profile set
✅ SC Launched
🤖 Starting SPU: (1/1) \                                                                                                                                                                                                                                                   ✅ 1 SPU launched
🎯 Successfully installed Local Fluvio cluster

$ fluvio cluster start   # fails as intended
📝 Running pre-flight checks
    📝 Checking Fluvio Local Installation \                                                                                                                                                                                                                                       found existing fluvio-run process. pid: 80138
       found existing fluvio-run process. pid: 80136
    ❌ Check Fluvio Local Installation failed Local Fluvio cluster still running
    ❌ Check Clean Fluvio Local Installation failed Local Fluvio cluster wasn't deleted. Use 'resume' to resume created cluster or 'delete' before starting a new one
💔 Some pre-flight check failed!
Preflight check failed

$ fluvio cluster shutdown 
fluvio cluster shutdown
Removed spu monitoring socket: /tmp/fluvio-spu.sock
Uninstalled fluvio local components

$ fluvio cluster resume
 -                                                                                                                                                                                                                                                                             ✅ Local Fluvio is not installed
    ❌ Check Clean Fluvio Local Installation failed Local Fluvio cluster wasn't deleted. Use 'resume' to resume created cluster or 'delete' before starting a new one
💔 Some pre-flight check failed!
❌ Resume failed with Preflight check failed
```

**Comment by avikam** [comment]
> This sequence fails to resume:

working on a bat test. I think it might suffer from version discrepancy between (stable) and (dev), but valuable to have nonetheless.

**Comment by digikata** [comment]
Yes, the test could be saved in an "incoming" directory that is maybe only run for new versions, then it can be moved in a later PR.

**Review by digikata — APPROVED** [review]
Looks great!  It's a nice improvement in the local cluster shutdown/resume behavior @avikam

**Pull request merged**
