### PR TITLE
[Merged by Bors] - fix: use relative paths in generated package-meta

### LINKED ISSUE #3119: Relative paths in auto-generated `package-meta` in `cdk` and `smdk` tools
Currently, when there is no `package-meta.yaml` file, `cdk` and `smdk` auto-generate it on `publish` step. 
Paths there are relative to the current directory, which is no longer valid behaviour. Need to reflect there the way how it works now: paths are relative to the `package-meta.yaml` file.

### PR DESCRIPTION
**Pull request by galibey**
Fixes #3119

### CODE REVIEW

**Comment by digikata** [comment]
Can you add a "publish --pack" step to the smdk smoke tests for regression coverage? 

In `tests/cli/smdk_smoke_tests/smdk-basic.bats` add the following as a last step for at least one test case:
```
    run $SMDK_BIN publish --pack
    assert_success
```

**Comment by galibey** [comment]
It turned out that in `smdk` cli tests the crate is inside the workspace. This case wasn't supported by `smdk publish`. So I added this support in the same way as it is done for `cdk publish`.

**Review by digikata — APPROVED** [review]
nice! LGTM

**Review by sehz — APPROVED** [review]

**Pull request closed without merging**
