### PR TITLE
[Merged by Bors] - Use brew update to use GH packages

### PR DESCRIPTION
**Pull request by nicholastmosher**
https://twitter.com/i/web/status/1380244628151037953

### CODE REVIEW

**Comment by nicholastmosher** [comment]
@simlay make sure you use the regular Github review button to approve the PR, then use `bors r+` again

**Review by simlay — APPROVED** [review]
pew pew

**Comment by simlay** [comment]
> pew pew

wait, I was suppose to write bors r+ there

**Review by simlay — APPROVED** [review]
bors r+

**Pull request closed without merging**
