### PR TITLE
[Merged by Bors] - Add windows target to github release

### LINKED ISSUE #1295: Add Windows CLI to release CI
In #1218, we added windows support to the CLI. Let's add it to the release CI.

### PR DESCRIPTION
**Pull request by simlay**
Closes #1295. I think this is all that's needed?

### CODE REVIEW

**Review by nicholastmosher — APPROVED** [review]
I _think_ that should work, I'm pretty sure the publisher flow will pick that up

**Review by sehz — CHANGES_REQUESTED** [review]
add to `github_release` job

**Review by sehz — APPROVED** [review]
sorry.  this is right patch

**Pull request closed without merging**
