### PR TITLE
[Merged by Bors] - Add linger and batch size config to `fluvio produce`

### LINKED ISSUE #2257: Expose producer batch settings in CLI
We have batch size and linger in the [`TopicProducerConfigBuilder`](https://docs.rs/fluvio/0.12.6/fluvio/struct.TopicProducerConfigBuilder.html)

We already use [`.topic_producer_with_config()`](https://docs.rs/fluvio/0.12.6/fluvio/struct.Fluvio.html#method.topic_producer_with_config) to build a producer in the CLI, so we can easily add in batch size and linger.

### PR DESCRIPTION
**Pull request by tjtelan**
Resolves #2257

### CODE REVIEW

**Review by morenol — APPROVED** [review]
lgtm!

**Review by sehz — APPROVED** [review]
LGTM

**Comment by morenol** [comment]
bors ping

**Pull request closed without merging**
