### PR TITLE
Rename cluster install to start, uninstall to delete

### LINKED ISSUE #507: rename cluster `install` and `uninstall`
`install` as `start`
`uninstall` as `delete`

### PR DESCRIPTION
**Pull request by nicholastmosher**
Closes #507

### CODE REVIEW

**Comment by nicholastmosher** [comment]
@sehz I believe this is failing because the GH action runner is using `ci.yml` from master, but I need to update it here. How can I make this run using the `ci.yml` from this branch?

**Comment by sehz** [comment]
Github is running `ci` workflow for each branch not from master

**Comment by sehz** [comment]
CI is failing because of this: 
```Run FLV_CMD=true ./target/release/fluvio cluster install --setup --local --develop
9
error: The subcommand 'install' wasn't recognized
10
	Did you mean 'uninstall'?
11

12
If you believe you received this message in error, try re-running with 'fluvio cluster -- install'`
```
Test runner need to be updated to reflect command renaming

**Review by sehz — APPROVED** [review]

**Comment by nicholastmosher** [comment]
@sehz are you sure that GH is launching using the CI file from this branch? This is the failure right now:

image

But I updated that line in `.github/workflows/ci.yml`:

```
      - name: Setup installation pre-requisites
        run: |
          FLV_CMD=true ./target/release/fluvio cluster start --setup --local --develop
```

Not sure what to do about this

**Review by sehz — APPROVED** [review]

**Pull request merged**
