### PR TITLE
[Merged by Bors] - Add `AtMostOnce` and `AtLeastOnce` delivery semantics

### PR DESCRIPTION
**Pull request by galibey**
Added two delivery semantics to Producer:
     1. `AtMostOnce` - we send records and do not wait for a response. To wait for the response, one could use ProduceOutput::wait after sending the record.     
     2. `AtLeastOnce` - we send records, wait for the response and retry if a network error occurs.     
     
The default retry policy:
retries: 4,
max timeout: 300s
delays sequence: 20ms, 400ms, 8s, 160s (Exponential Backoff)

Related #2481

### CODE REVIEW

**Review by morenol — APPROVED** [review]
Nice work! Looks good to me!

**Review by tjtelan — APPROVED** [review]
good job

**Review by sehz — APPROVED** [review]
LGTM.  Nice work!

**Comment by sehz** [comment]
Can you link to existing issue?

**Pull request closed without merging**
