### PR TITLE
feat: print causes for errors

### PR DESCRIPTION
**Pull request by ozgrakkurt**
closes https://github.com/infinyon/fluvio/issues/3353

This is WIP, but requesting reviews to get feedback on the approach.

I'm just doing this pattern:
```
#[error("Failed to parse format string: {0}")]
TemplateError(#[from] TemplateError),
```

### CODE REVIEW

**Comment by digikata** [comment]
I think this is fine for this error, but I'd mention that each error needs to be looked at individually. Sometimes you don't want to print the error info directly, and the code injecting the error or passing it along should inject context.

**Comment by sehz** [comment]
This is an improvement.  However, some of these errors are unnecessary if we convert to anyhow

**Comment by ozgrakkurt** [comment]
To keep PR simple, is it ok to just do this on all errors for this PR and then do a selective deletion of extra info?

**Comment by sehz** [comment]
Converting to anyhow will be more productive

**Comment by sehz** [comment]
Yes, unless there is an explicit need for modeling error.  The vast majority of these are just passed thru which are unnecessary

**Comment by ozgrakkurt** [comment]
> Yes, unless there is an explicit need for modeling error. The vast majority of these are just passed thru which are unnecessary

got it, makes sense, we don't even match on any of them probably

**Review by nacardin — APPROVED** [review]
LGTM

**Review by digikata — APPROVED** [review]

**Comment by ozgrakkurt** [comment]
closing this in favor of smaller PRs per crate

**Pull request closed without merging**
