### PR TITLE
[Merged by Bors] - feat: explicit set of errors to retry

### PR DESCRIPTION
**Pull request by galibey**
The current default time to wait for Fluvio Socket is 5 minutes, and until that time, if there is a network connectivity issue, it does not report an error. It seems too coarse, it doesn't align well with retries. For the producer, for example, we set a whole timeout for all retries is 5 minutes.

This PR is a proposal to decrease this value and explicitly define the set of socket errors that we want to retry.

Related #3124

### CODE REVIEW

**Review by sehz — APPROVED** [review]
LGTM.  check if need to bump up crate version.

**Review by sehz — COMMENTED** [review]
Think just patch version changes is required

**Review by morenol — APPROVED** [review]

**Comment by galibey** [comment]
I will merge it after the 0.10.7 release is finished.

**Comment by galibey** [comment]
bors retry

**Pull request closed without merging**
