### PR TITLE
[Merged by Bors] - Change C compiler to Zig

### PR DESCRIPTION
**Pull request by nacardin**
In order to fix musl build issues on newer GCC, this PR changes C compiler to Zig and Linker to LLD 11.

Please test on various OSes.

### CODE REVIEW

**Comment by sehz** [comment]
@sehz try this on Mac

**Comment by sehz** [comment]
fails to compile on Mac:


```	--features cluster_components_rustls --bin fluvio --target x86_64-unknown-linux-musl
   Compiling ring v0.16.15
   Compiling idna v0.2.0
   Compiling async-global-executor v1.4.3
   Compiling async-fs v1.5.0
   Compiling async-net v1.5.0
   Compiling tokio v0.2.22
   Compiling time-macros v0.1.1
   Compiling aes v0.6.0
   Compiling hkdf v0.10.0
   Compiling which v4.0.2
   Compiling futures-util v0.3.8
   Compiling der-parser v4.1.0
error: failed to run custom build command for `ring v0.16.15`
Caused by:
  process didn't exit successfully: `/fluvio/target/debug/build/ring-84ee798471bc431b/build-script-build` (exit code: 101)
  --- stdout
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-musl")
  HOST = Some("x86_64-apple-darwin")
  CC_x86_64-unknown-linux-musl = None
  CC_x86_64_unknown_linux_musl = None
  TARGET_CC = Some("clang")
  CFLAGS_x86_64-unknown-linux-musl = None
  CFLAGS_x86_64_unknown_linux_musl = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
11:41
 ENV __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
  running "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=x86_64-unknown-linux-musl" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-U_FORTIFY_SOURCE" "-DNDEBUG" "-c" "-o/fluvio/target/x86_64-unknown-linux-musl/debug/build/ring-060568c9c9dc5f55/out/aes_nohw.o" "crypto/fipsmodule/aes/aes_nohw.c"

**Comment by nacardin** [comment]
No longer needed since https://github.com/infinyon/fluvio/pull/521 remove `ring` dependency.

**Comment by nacardin** [comment]
We now have other dependencies that use CC

**Comment by nacardin** [comment]
Updated this to use zig/lld. Seems to work everywhere as long as `ld.lld` points to an LLVM 11 install. LLVM 12 does not work. I would like to add a pre-check to make sure that `ld.lld` is from LLVM 11.

**Review by sehz — APPROVED** [review]
Very nice work!  This finally fixes long standing cross compilation issues

**Review by sehz — CHANGES_REQUESTED** [review]
Can you add to changelog?

**Comment by ajhunyady** [comment]
Does this help with the Raspberry Pi build?

**Comment by sehz** [comment]
Yes, it should cross compile to Raspberry on on any supported OS (Linux, Mac, etc)

**Comment by ajhunyady** [comment]
Ok, I look forward to the Raspberry Pi build for my weekend project. Any plans to add that back to pre-built images?

**Comment by nacardin** [comment]
> Can you add to changelog?

Updated

**Comment by sehz** [comment]
there is merge conflict

**Comment by nacardin** [comment]
> there is merge conflict

resolved

**Review by sehz — APPROVED** [review]
LGTM

**Comment by sehz** [comment]
need rebase again with other PR landed first

**Pull request closed without merging**
